// <auto-generated />
using System;
using LabAcademiaAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabAcademiaAPI.Migrations
{
    [DbContext(typeof(LabAcademiaContext))]
    partial class LabAcademiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabAcademiaAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Carga")
                        .HasColumnType("double precision");

                    b.Property<int>("CodigoTreino")
                        .HasColumnType("integer");

                    b.Property<bool?>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int?>("Repeticao")
                        .HasColumnType("integer");

                    b.Property<int?>("Series")
                        .HasColumnType("integer");

                    b.Property<double?>("Tempo")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTreino");

                    b.ToTable("Exercicios", "academia");
                });

            modelBuilder.Entity("LabAcademiaAPI.Models.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Treino")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Historicos", "academia");
                });

            modelBuilder.Entity("LabAcademiaAPI.Models.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<char>("Codigo")
                        .HasColumnType("character(1)");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Treinos", "academia");
                });

            modelBuilder.Entity("LabAcademiaAPI.Models.UsuariosTreinos", b =>
                {
                    b.Property<int>("CodigoTreino")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoUsuario")
                        .HasColumnType("integer");

                    b.HasIndex("CodigoTreino");

                    b.ToTable("UsuariosTreinos", "academia");
                });

            modelBuilder.Entity("LabAcademiaAPI.Models.Exercicio", b =>
                {
                    b.HasOne("LabAcademiaAPI.Models.Treino", "Treinos")
                        .WithMany()
                        .HasForeignKey("CodigoTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("LabAcademiaAPI.Models.UsuariosTreinos", b =>
                {
                    b.HasOne("LabAcademiaAPI.Models.Treino", "Treinos")
                        .WithMany()
                        .HasForeignKey("CodigoTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
